### ISSUE TITLE
NEXT-10109 - Remove hover from non links 

### ISSUE THREAD

**Issue by juliankoehn** [shopware/shopware#1241]
https://github.com/shopware/platform/commit/616588256743b22e27879a94042d01293e3599a4

L38 should be `a:hover` not `a&:hover`

results in compiler issues `Invalid CSS after "a": expected "{", was "&"`

@tinect @bneumann97

**Comment by tinect** [comment]
Hey @juliankoehn Don't know what's wrong on your side, but it works as it's posted.
Please note: your change will not have any result.

**Comment by tinect** [comment]
Let me explain:
`a&:hover` results in `a.cart-item-label:hover` which is correct
`a:hover` results in `.cart-item-label a:hover` which is wrong

**Comment by juliankoehn** [comment]
If this is the expected output:
```css
a.cart-item-label:hover {
    color: #008490;
    text-decoration: none;
}
```

Should this be 
```scss
.cart-item-label {
    color: $body-color;
    font-weight: $font-weight-bold;
    @at-root {
        a#{&}:hover {
            color: $primary;
            text-decoration: none;
        }
    }
}
```

https://sass-lang.com/documentation/at-rules/at-root
