### ISSUE TITLE
Storefront not accessible trough IP in Shopware 6

### ISSUE THREAD

**Issue by Danoctum** [shopware/shopware#1475]
**Description**  
I have installed a fresh Shopware 6 installation using the Dockware Docker container on my Ubuntu server. I'm using the following config in my docker-compose.yml file:

```
version: "3"

services:

    shopware:
      # use either tag "latest" or any other version like "6.1.5", ...
      image: dockware/dev:latest
      container_name: shopware
      ports:
         - 80:80
         - 3306:3306
         - 22:22
         - 8888:8888
         - 9999:9999
      volumes:
         - "db_volume:/var/lib/mysql"
         - "shop_volume:/var/www/html"
      networks:
         - web
      environment:
         # default = 0, recommended to be OFF for frontend devs
         - XDEBUG_ENABLED=1
         # default = latest PHP, optional = specific version
         - PHP_VERSION=7.4

volumes:
  db_volume:
    driver: local
  shop_volume:
    driver: local

networks:
  web:
    external: false
```

Everything in the admin panel works fine, but I can't access the storefront trough ip. It throws an 500 internal server error when being accessed, and I can't find any logs in the Shopware admin panel. The IP/admin route works fine though.

Why does this not work? Does shopware not allow the storefront to be directly accessed by IP? I don't have a domain at the moment to test this theory with.

[Someone also made a ticket on this error on the Shopware forum.](https://forum.shopware.com/discussion/72678/internal-500-error-when-rooting-to-shopware-public-trying-to-open-page-with-ip-address)
