### ISSUE TITLE
NEXT-6651 - Using remote filesystem breaks frontend and backend

### ISSUE THREAD

**Issue by tiwac100** [shopware/shopware#466]
**Description**  
When using a remote filesystem (S3, Google Cloud, CDN) according to the [docs](https://docs.shopware.com/en/shopware-platform-dev-en/how-to/use-s3-datastorage) the frontend and backend (plugins) styles and javascript are broken.

This is because Shopware saves these files on the remote filesystem on theme compilation but the URLs still point to the relative `/themes` (frontend) and `/bundles` (backend) paths.

**Possible Solution**  
Respect the filesystem when generating asset URLs or save compiled theme files always on local.

**Additional context**  
shopware.yaml:
```
shopware:
  filesystem:
    public:
      type: "amazon-s3"
      config:
        bucket: "%env(AWS_PUBLIC_BUCKET)%"
        region: "%env(AWS_PUBLIC_REGION)%"
        options:
          visibility: "public"
    private:
      type: "amazon-s3"
      config:
        bucket: "%env(AWS_PRIVATE_BUCKET)%"
        region: "%env(AWS_PRIVATE_REGION)%"
        options:
          visibility: "private"
  cdn:
    url: "%env(SHOPWARE_CDN)%"
```

**Comment by shopwareBot** [comment]
Hello,

thank you for creating this issue.
I have opened a ticket on our Issue Tracker for you. See the ticket link: https://issues.shopware.com/issues/NEXT-6651

Please use this ticket to track the state of your issue.

**Comment by tiwac100** [comment]
Just an additional note: this also affects sitemaps and all other things Shopware places in the public directory.

**Comment by htuscher** [comment]
Yes the public files (media) and assets are mixed up. But they are not similar => they should have used a different filesystem. 
The Symfony asset component that is used is not using Flysystem internally. Therefore all asset links generated in the frontend will always assume local files.

A clean solution would be to introduce a new filesystem service for static resources and assets and completely separate them from media.

```yaml
parameters:
    filesystem_local_public:
        type: 'local'
        config:
            root: '%kernel.project_dir%/public'

services:
    filesystem.local.public:
        class: 'League\Flysystem\FilesystemInterface'
        factory: ['@Shopware\Core\Framework\Adapter\Filesystem\FilesystemFactory', 'factory']
        arguments:
            - '%filesystem_local_public%'

    Shopware\Storefront\Theme\ThemeCompiler:
        arguments:
            - '@filesystem.local.public'
            - '@Shopware\Storefront\Theme\ThemeFileResolver'
            - '%kernel.cache_dir%'
            - '%kernel.debug%'
```

Is just one workaround atm for that issue.

**Comment by rawdha-93** [comment]
@hhoechtl Do you mean that we have to create a new filesystem in /config/packages? or just replace the content of shopware.yml?

**Comment by htuscher** [comment]
@rawdha-93 the snippet does create a new local filesystem service called `filesystem.local.public`. That's the way you define a Flysystem based filesystem.

This new forced local filesystem is then forcefully injected as argument for the theme compiler so the theme compiler doesn't use the public filesystem and loads the generated CSS files to the S3 bucket used for the public filesystem, from where the CSS files can't be loaded.

The implementation for including non local CSS and assets is simply missing.

**Comment by AlexBa** [comment]
I got the same problem! But the quick fix of @hhoechtl  is working.

**Comment by htuscher** [comment]
And a new service has been introduced, that needs a workaround:

```yaml
    filesystem.local.public:
        class: 'League\Flysystem\FilesystemInterface'
        factory: ['@Shopware\Core\Framework\Adapter\Filesystem\FilesystemFactory', 'factory']
        arguments:
            - '%filesystem_local_public%'
    Shopware\Storefront\Theme\ThemeCompiler:
        arguments:
            $publicFilesystem: '@filesystem.local.public'
            $cacheDir: '%kernel.cache_dir%'
            $debug: '%kernel.debug%'
    Shopware\Core\Framework\Plugin\Util\AssetService:
        arguments:
            $filesystem: '@filesystem.local.public'
```

**Comment by TaiKamilla** [comment]
> And a new service has been introduced, that needs a workaround:
> 
> ```yaml
>     filesystem.local.public:
>         class: 'League\Flysystem\FilesystemInterface'
>         factory: ['@Shopware\Core\Framework\Adapter\Filesystem\FilesystemFactory', 'factory']
>         arguments:
>             - '%filesystem_local_public%'
>     Shopware\Storefront\Theme\ThemeCompiler:
>         arguments:
>             $publicFilesystem: '@filesystem.local.public'
>             $cacheDir: '%kernel.cache_dir%'
>             $debug: '%kernel.debug%'
>     Shopware\Core\Framework\Plugin\Util\AssetService:
>         arguments:
>             $filesystem: '@filesystem.local.public'
> ```

@hhoechtl 
That fix does not work for me

I get this when I clear cache

```
 // Clearing the cache for the prod environment with debug false                                                        


In DefinitionErrorExceptionPass.php line 54:
                                                                                                                                                           
  Invalid constructor argument 3 for service "Shopware\Storefront\Theme\ThemeCompiler": argument 2 must be defined before. Check your service definition.  
                                                                                                                                                           

cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

```

**Comment by htuscher** [comment]
Interested

**Comment by vanWittlaer** [comment]
interested

**Comment by janbuecker** [comment]
As @hhoechtl said, it's a little bit mixed up. Assets and media files are the same in general, but they are handled in different ways.

The assets, like compiled javascript and CSS, are handled by the Symfony asset system and needs to be configured accordingly. So in addition to the filesystem and CDN configuration, you need to update the Symfony asset configuration too:

**config/packages/symfony.yaml (for the OP's post)**
```yaml
framework:
  assets:
    base_urls:
      - "%env(SHOPWARE_CDN)%"
```
