### ISSUE TITLE
run development/bin/setup  non interactive

### ISSUE THREAD

**Issue by musab1** [shopware/shopware#65]
Hi

i could not figure out how to run the setup tool with -n option. 
how can i pass the parameters to be able to script that. 

Greets
Musa

**Comment by keulinho** [comment]
Hi,
all that the setup script does is generate a `.psh.yaml.override` file for you through an interactive process.
The generated file may look like this:
```yaml
const:
  APP_ENV: "dev"
  APP_URL: "http://shopware.local"
  DB_HOST: "localhost"
  DB_PORT: "3306"
  DB_NAME: "shopware"
  DB_USER: "app"
  DB_PASSWORD: "root"
```
If you want to script this simply add a `.psh.yaml.override` with your values to the root directory of the installation (where you cloned shopware/development). 
It must be in the same folder as the original `.psh.yaml.dist` and it overrides the const values defined in that file.
You can take a look in the `.psh.yaml.dist` if you need to customize your build process further, but most of the other consts defined there are for development purposes.
After your `.psh.yaml.override` file is in place simply run the installation script with `./psh.phar install`.
