### ISSUE TITLE
Storefront slider items are popping up underneath each over on page load

### ISSUE THREAD

**Issue by benjamin-ott** [shopware/shopware#924]
**Description**  
On page load all the slider items (e.g. image slider on a cms page) are popping up underneath each over until the slider js is fully initialized.

**Example**  
Hide all slider items (except the first one) via scss until the slider is fully initialized.

**Comment by mariusfaber98** [comment]
I have created some CSS that would solve the problem. Without any layout shift by styling the slider without JS Exactly the same as the initialized slider with JS.

The only problem is that the number of products inside the slider would be needed to be statically defined what could be a problem in the future if Shopware will add some functionally to change the number of products inside a slider. 

So the best solution would probably be to generate the CSS dynamically on the server depending on how many products are inside a slider. But I am not sure if this is really the solution that should be inside the core. Since it feels like a bit of a hacky solution to solve this problem this way. 

```scss
.product-slider-container {
    display: flex;
}

.product-slider:not(.js-slider-initialized) {
    margin-right: -30px;
}

.product-slider-container:not(.tns-slider) {
    width: calc(700%);
    display: flex;
}

.product-slider-item:not(.tns-item) {
    width: calc(14.2857%);
    padding-right: 30px;
}

.cms-element-product-slider {
    overflow: hidden;
}

.product-slider-controls-next:not([data-controls='next']) {
    right: 20px;
}

@include media-breakpoint-up(md) {
    .product-slider-container:not(.tns-slider) {
        width: calc(550%);
    }

    .product-slider-item:not(.tns-item) {
        width: calc(9.09091%);
    }
}

@include media-breakpoint-up(lg) {
    .product-slider-container:not(.tns-slider) {
        width: calc(500%);
    }

    .product-slider-item:not(.tns-item) {
        width: calc(6.66667%);
    }
}

```
